server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: ${AUTH_SERVICE_NAME:auth-service}
  config:
    import: "configserver:"
  cloud:
    config:
      #label: sleuth
      uri: http://${CONFIG_SERVICE_NAME:localhost}:${CONFIG_SERVICE_PORT:8081}
      username: ${CONFIG_SERVICE_USER:root}
      password: ${CONFIG_SERVICE_PASSWORD:root}
    fail-fast: true
    loadbalancer:
      ribbon:
        enabled: false

logging:
  file:
    path: /var/log/online-store/${spring.application.name}
